# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_dev_main.ui'
#
# Created: Mon Sep  2 04:42:25 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName(_fromUtf8("TabWidget"))
        TabWidget.resize(449, 398)
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(100, 50, 301, 27))
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(15, 55, 59, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(0, 120, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 120, 301, 27))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 170, 98, 27))
        self.pushButton_3.setDefault(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.line = QtGui.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(20, 200, 401, 31))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.progressBar = QtGui.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(20, 260, 401, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 66, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.toolButton = QtGui.QToolButton(self.tab)
        self.toolButton.setGeometry(QtCore.QRect(410, 50, 23, 25))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.toolButton_2 = QtGui.QToolButton(self.tab)
        self.toolButton_2.setGeometry(QtCore.QRect(410, 120, 23, 25))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.textBrowser = QtGui.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(20, 300, 411, 41))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        TabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.checkBox = QtGui.QCheckBox(self.tab1)
        self.checkBox.setGeometry(QtCore.QRect(210, 210, 151, 22))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.tab1)
        self.checkBox_2.setGeometry(QtCore.QRect(40, 240, 171, 22))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.tab1)
        self.checkBox_3.setGeometry(QtCore.QRect(210, 180, 221, 22))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.pushButton_4 = QtGui.QPushButton(self.tab1)
        self.pushButton_4.setGeometry(QtCore.QRect(370, 300, 51, 27))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab1)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 45, 301, 27))
        self.lineEdit_3.setText(_fromUtf8(""))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tab1)
        self.lineEdit_4.setGeometry(QtCore.QRect(100, 100, 301, 27))
        self.lineEdit_4.setText(_fromUtf8(""))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_4 = QtGui.QLabel(self.tab1)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 59, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab1)
        self.label_5.setGeometry(QtCore.QRect(0, 105, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.toolButton_3 = QtGui.QToolButton(self.tab1)
        self.toolButton_3.setGeometry(QtCore.QRect(410, 44, 23, 25))
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.toolButton_4 = QtGui.QToolButton(self.tab1)
        self.toolButton_4.setGeometry(QtCore.QRect(410, 100, 23, 25))
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.pushButton = QtGui.QPushButton(self.tab1)
        self.pushButton.setGeometry(QtCore.QRect(290, 300, 61, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.tab1)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 300, 98, 27))
        self.pushButton_2.setAcceptDrops(False)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setDefault(True)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.checkBox_5 = QtGui.QCheckBox(self.tab1)
        self.checkBox_5.setGeometry(QtCore.QRect(40, 180, 151, 22))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox_6 = QtGui.QCheckBox(self.tab1)
        self.checkBox_6.setGeometry(QtCore.QRect(40, 210, 151, 22))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        TabWidget.addTab(self.tab1, _fromUtf8(""))

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(_translate("TabWidget", "uSSync", None))
        self.label.setText(_translate("TabWidget", "   Source", None))
        self.label_2.setText(_translate("TabWidget", "  Destination", None))
        self.pushButton_3.setText(_translate("TabWidget", "Sync Now", None))
        self.label_3.setText(_translate("TabWidget", "Progress", None))
        self.toolButton.setText(_translate("TabWidget", "...", None))
        self.toolButton_2.setText(_translate("TabWidget", "...", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Basic", None))
        self.checkBox.setText(_translate("TabWidget", "Always Checksum", None))
        self.checkBox_2.setText(_translate("TabWidget", "Preserve permissions", None))
        self.checkBox_3.setText(_translate("TabWidget", "Preserve Time", None))
        self.pushButton_4.setText(_translate("TabWidget", "New", None))
        self.label_4.setText(_translate("TabWidget", "   Source", None))
        self.label_5.setText(_translate("TabWidget", "  Destination", None))
        self.toolButton_3.setText(_translate("TabWidget", "...", None))
        self.toolButton_4.setText(_translate("TabWidget", "...", None))
        self.pushButton.setText(_translate("TabWidget", "Open", None))
        self.pushButton_2.setText(_translate("TabWidget", "Sync Now", None))
        self.checkBox_5.setText(_translate("TabWidget", "Disable Recursion", None))
        self.checkBox_6.setText(_translate("TabWidget", "Verbose ", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab1), _translate("TabWidget", "Advanced", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TabWidget = QtGui.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())

